on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: build app
        working-directory: ./app
        run: >
          npm ci &&
          npm run build;

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: d5d4a686432762d8a717a062688b2d4d
          projectName: todo-app
          directory: ./app/build
